services:
  db:
    image: postgres:16
    env_file: .env
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  pgdata:
